#!/bin/bash

echo "🔬 Mysticeti ASR Validation Plan"
echo "================================"
echo ""
echo "To determine if ASR is 'real', we need to:"
echo ""
echo "1. BASELINE TEST (No Attack):"
echo "   • Expected ASR: ~50% (random ordering)"
echo "   • If baseline ≠ 50%, measurement method is biased"
echo ""
echo "2. EXCLUSION EFFECTIVENESS:"
echo "   • Count 'Excluding victim decision block' logs"
echo "   • Calculate: exclusions / total_victim_decisions"
echo "   • Expected: ~99.8% if working"
echo ""
echo "3. VICTIM BLOCK COUNT:"
echo "   • With attack: Count victim blocks in commits"
echo "   • Without attack: Count victim blocks in commits"
echo "   • Expected: victim_with_attack < victim_baseline"
echo ""
echo "4. LEADER ANALYSIS:"
echo "   • Count victim leaders: committed vs skipped"
echo "   • With attack: More skips expected"
echo ""
echo "5. QUORUM IMPACT:"
echo "   • Count 'maintain quorum' forced inclusions"
echo "   • High count = quorum limiting exclusion"
echo ""
echo "6. MULTIPLE RUNS:"
echo "   • Run 10+ times, calculate average"
echo "   • Check standard deviation"
echo "   • Low stddev = stable measurement"
echo ""

# Quick check: Are we getting realistic ratios?
echo "📊 Quick Validation:"
echo ""
echo "Network: 13 nodes (4 attackers, 3 victims, 6 honest)"
echo "Stake ratio: Attackers 4/13 = 30.8%, Victims 3/13 = 23.1%"
echo ""
echo "Expected without attack:"
echo "  • Attacker blocks: ~30.8% of blocks"
echo "  • Victim blocks: ~23.1% of blocks"
echo ""
echo "Expected with attack (if exclusion works):"
echo "  • Attacker blocks: >30.8% (due to exclusion)"
echo "  • Victim blocks: <23.1% (due to exclusion)"
echo ""
echo "If victim blocks are ~23.1% → Exclusion NOT working"
echo "If victim blocks are <23.1% → Exclusion may be working"
echo ""

