"""Diff-scope guard for the v2 Rust edits in code/bullshark/.

The protocol-modification invariant (CLAUDE.md) restricts paper-2 to a
*localized* extension of paper-1's attacker hooks. This test asserts that no
Rust file outside the approved P1a allowlist has been modified under
code/bullshark/. It runs against `git status` so it catches both tracked
modifications and stray new files.

If you legitimately need to touch a new Bullshark file, update
`ALLOWED_MODIFIED` *and* the integration-plan doc, then explain the rationale
in the PR. Do not silently widen the allowlist.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
BULLSHARK_ROOT = "code/bullshark/"

# Approved changeset, relative to repo root.
# Updated v3 R-P2.1: adds mev_attack_metrics.rs for the FINAL_COMMITTED_ORDER
# marker (per-policy ASR is computed Python-side from this JSON).
ALLOWED_MODIFIED: set[str] = {
    "code/bullshark/Cargo.lock",  # auto-generated by cargo when deps change
    "code/bullshark/consensus/core/Cargo.toml",  # adds ureq + serde_json
    "code/bullshark/consensus/core/src/core.rs",  # the V2_COORDINATOR_URL branch
    "code/bullshark/consensus/core/src/lib.rs",  # adds the mod declaration
    "code/bullshark/consensus/core/src/v2_coordinator_client.rs",  # new module
    "code/bullshark/consensus/core/src/mev_attack_metrics.rs",  # v3 R-P2.1 marker
    # DS4/DS5 withholding: env-gated proposer hooks (SILENT_EXCEPT_LEADER / slw)
    # in core.rs (already listed) + a test-only driver file. Both are within the
    # legitimate action set (a withheld proposal is the ordinary slow-link case)
    # and byte-identical to upstream when neither env trigger is set.
    "code/bullshark/consensus/core/src/withholding_attack_test.rs",  # DS4/DS5 ASR tests
    # DS13 skewed stake (env-gated STAKE_PROFILE, config-only committee build)
    # + DS14 WAN latency (env-gated LATENCY_MS delay-only send). Both stay in the
    # legitimate deployment/config space; byte-identical to upstream when unset.
    "code/bullshark/consensus/core/src/fissure_attack_test.rs",  # DS13 STAKE_PROFILE
    "code/bullshark/consensus/core/src/network/tonic_network.rs",  # DS14 LATENCY_MS
    # Index-tax defense eval: env-gated FIX_TIEBREAK in the sub-dag block sort
    # (digest tiebreak instead of author index). This is a DEFENSE knob, not an
    # attack; the upstream comment already sanctions "any deterministic & stable
    # algorithm"; default path is byte-identical when FIX_TIEBREAK is unset. It
    # touches no validity/quorum/signature predicate. Mirrors the Sui fork's gate.
    "code/bullshark/consensus/core/src/commit.rs",  # FIX_TIEBREAK (index-tax fix)
    # Index-tax leader-mode eval: env-gated STAKE_BASED_LEADER in elect_leader's
    # #[cfg(test)] arm — implements the file's own upstream TODO (use the staked
    # schedule in tests). Test-build only, default path (round-robin) byte-identical
    # when unset; production arm untouched. Touches no validity/quorum predicate.
    "code/bullshark/consensus/core/src/leader_schedule.rs",  # STAKE_BASED_LEADER
}

# Known orphan deletions that existed before P1a started. These are not
# something P1a created; tracked here only to keep the test honest.
ALLOWED_PREEXISTING_DELETIONS: set[str] = {
    "code/bullshark/CLAUDE.md",
}


def _git_porcelain() -> list[tuple[str, str]]:
    """Return [(status_code, path), ...] from `git status --porcelain`."""
    out = subprocess.run(
        ["git", "status", "--porcelain", "--untracked-files=all", "code/bullshark/"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    rows: list[tuple[str, str]] = []
    for line in out.stdout.splitlines():
        if not line.strip():
            continue
        # status is the first 2 chars; path starts at index 3.
        status = line[:2]
        path = line[3:].strip()
        # Renames take the "old -> new" form; we only care about the new path.
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        rows.append((status, path))
    return rows


def test_only_approved_bullshark_files_modified():
    rows = _git_porcelain()
    unapproved: list[tuple[str, str]] = []
    for status, path in rows:
        if not path.startswith(BULLSHARK_ROOT):
            continue
        # Pure deletions (status "D " or " D") get checked against the orphan list.
        if status.strip() == "D":
            if path in ALLOWED_PREEXISTING_DELETIONS:
                continue
            unapproved.append((status, path))
            continue
        if path in ALLOWED_MODIFIED:
            continue
        unapproved.append((status, path))
    assert not unapproved, (
        "Unapproved Bullshark changes detected. Each new path requires an "
        "explicit allowlist update + integration-plan rationale.\n"
        + "\n".join(f"  {s} {p}" for s, p in unapproved)
    )


def test_core_rs_v2_branch_present():
    """Sanity: the V2 override block must actually be in core.rs.

    If someone reverts the block, this test fails immediately rather than
    silently going back to paper-1 behavior across the multi-policy work.
    """
    core_rs = REPO_ROOT / "code" / "bullshark" / "consensus" / "core" / "src" / "core.rs"
    text = core_rs.read_text()
    assert 'env::var("V2_COORDINATOR_URL")' in text, (
        "core.rs missing the V2_COORDINATOR_URL branch -- p1a.4 revert?"
    )
    assert "crate::v2_coordinator_client::lookup_policy" in text, (
        "core.rs missing the lookup_policy call site -- p1a.4 revert?"
    )


def test_v2_coordinator_client_module_present():
    f = REPO_ROOT / "code" / "bullshark" / "consensus" / "core" / "src" / "v2_coordinator_client.rs"
    assert f.exists(), "v2_coordinator_client.rs missing"
    text = f.read_text()
    assert "pub fn lookup_policy" in text
    # Honest-node 404 handling MUST stay -- it's load-bearing for the invariant.
    assert "ureq::Error::Status(404, _)" in text


def test_lib_rs_mod_present():
    f = REPO_ROOT / "code" / "bullshark" / "consensus" / "core" / "src" / "lib.rs"
    assert "mod v2_coordinator_client;" in f.read_text()
